-- Create table for AI Knowledge
CREATE TABLE IF NOT EXISTS public.ai_knowledge_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL, -- 'supplier', 'correction', etc.
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE public.ai_knowledge_base ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.ai_knowledge_base
    FOR SELECT USING (true);

CREATE POLICY "Enable all access for authenticated users" ON public.ai_knowledge_base
    FOR ALL USING (auth.role() = 'authenticated');


-- Seed Initial Data (The 39 Suppliers)
INSERT INTO public.ai_knowledge_base (type, content, metadata) VALUES
('supplier', 'ABC Instrumentos Cirúrgicos LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'Açomix Metalúrgica Ltda', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'Agevet Comercial de Produtos Veterinários Ltda', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'ARTIOLI E MARTINS COMERCIO DE IMPORTAÇÃO E EXPORTAÇÃO LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'ATACAMA IND E COM DE EQUIPAMENTOS LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'B.M.B. IND E COM DE COSMETICOS LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'Bicho Prime Pet Shop Ltda', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'BRASGROUP COMERCIAL LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'BRASIL PET COMERCIO EQUIP LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'BUBBLES PETS COMERCIO DE COSMETICOS E PRODUTOS DE PERFUMARIA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'C E COMERCIO DE EQUIPAMENTOS PROFISSIONAIS LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'CAT DOG CIA DE PRODUTOS VETERINARIOS LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'CLICKNEW INDUSTRIAL EIRELI', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'CLIPPERTEC INDL E COML LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'DAROS CORP IMPORTAÇÃO E EXPORTAÇÃO LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'DISTRIBUIDORA TECMASTER LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'FAME - FABRICA DE APARELHOS E MATERIAL ELETRICO LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'Fuentes com gesso fib tex eireli', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'GOLDEN DOG LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'Grooming Muito Pop Ltda', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'Helia Mara Verssuti', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'IMPORTACAO E EXP DE PROD PARA BELEZA LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'INOVEN INDUSTRIA COMERCIO E IMPORTACAO LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'Invicta Imports Ltda', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'LANCA BICHOS IMPORTACAO E EXPORTACAO LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'M & S IMPORTAÇÃO E EXPORTACAO DE PRODUTOS DE EMBELEZAMENTO', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'Maedi Comercio de Artigos de Embelezamento LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'MARLI NUNES DA SILVA - EPP', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'MEC INDUSTRIA MECANICA IMP. E EXP EIRELI', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'METALURGICA VENEZIA LTDA - ME', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'MOLDPET INDUSTRIA DE ARTIGOS PARA ANIMAIS LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'Omega Pet', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'PET RM COLARES E FOCINHEIRA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'Plenitude Manutenção de Maquinas LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'Ponteland', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'S M FERNANDES SANDUICHE', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'THCR COMERCIO IMPORTACAO E EXPORTACAO EIRELI', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'UNIQUE INDUSTRIA E COMERCIO LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'W.M. INDUSTRIA E COMERCIO DE PRODUTOS ELETRICOS', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'TRADECORP IMPORTADORA E EXPORTADORA LTDA', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'SECADORES PLENITUDE', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'RODONAVES TRANSPORTE', '{"category_id": 69, "category_name": "Fornecedores"}'),
('supplier', 'TECPET SOLUCOES TECNOLOGICAS', '{"category_id": 69, "category_name": "Fornecedores"}');
